### ISSUE TITLE
Make stream get return a stream directly

### ISSUE THREAD

**Issue by tpluscode** [rdf-ext/sparql-http-client#22]
In the current version (2.x), the `StreamQuery#get` is implemented to return a `Promise<Stream>`. This is a little awkward, and an anti pattern as it mixes two way for coding asynchronously

The proposal is to have the promise handled in the library so that stream query returns only a quad stream, unwrapped from the promise.

**Comment by cristianvasquez** [comment]
Also, the status returned from the endpoint is lost; what would be a good signature for this?

**Comment by bergos** [comment]
@cristianvasquez I think this is only relevant for non-2xx status codes, or do you see other use cases? The status code could be attached to the error object like it's done by the [http-errors](https://www.npmjs.com/package/http-errors) package. Then it's possible to handle all errors with the `error` event of the stream. HTTP errors will have the `status` property.

**Comment by bergos** [comment]
implemented in #58
